### ISSUE TITLE
CSRF token mismatch.

### ISSUE THREAD

**Issue by VoronovIgor** [anisAronno/multipurpose-admin-panel-boilerplate#7]
Hello, good idea ;)
But have err CSRF token
Example /forgot-password
            });
        }

        throw new TokenMismatchException('CSRF token mismatch.');
    }

    /**

**Comment by anisAronno** [comment]
"Hello,

Thank you for bringing up the issue regarding the CSRF token error. I apologize for the inconvenience, but I am unable to replicate the error on my end. To assist you further and provide a solution, I kindly request you to provide more details or a screenshot of the error you are encountering. This will help me better understand the issue and offer appropriate guidance.

Thank you for your cooperation, and I look forward to your response.

**Comment by OttyNY** [comment]
I receiving the same error. I just installed the laravel project but I can't login. Receive error 419 with relate to the CSRF token error. Please advise.

**Comment by anisAronno** [comment]
Thank you guys,

This is session issues. Just remove this line from the .env file.

SESSION_DOMAIN=http://www.admin-panel.test

then run this command,

php artisan optimize:clear

I hope solve this problem
