### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by oligirling** [anisAronno/multipurpose-admin-panel-boilerplate#9]
Any chance you have any screenshots of this?

**Comment by anisAronno** [comment]
![Screenshot 2023-11-22 at 12 48 15 PM (2)](https://github.com/anisAronno/multipurpose-admin-panel-boilerplate/assets/38912435/a9c12f25-3927-492d-9b76-bfd9827e8655)
<img width="1440" alt="Screenshot 2023-11-22 at 12 48 36 PM" src="https://github.com/anisAronno/multipurpose-admin-panel-boilerplate/assets/38912435/b6aaae6b-6390-43a0-82fa-2989867a421c">
<img width="1440" alt="Screenshot 2023-11-22 at 12 49 11 PM" src="https://github.com/anisAronno/multipurpose-admin-panel-boilerplate/assets/38912435/9ba7a1cf-1e3e-4b5b-afc0-df2cd9670670">
<img width="1440" alt="Screenshot 2023-11-22 at 12 49 16 PM" src="https://github.com/anisAronno/multipurpose-admin-panel-boilerplate/assets/38912435/f3054ea0-dc1b-4859-b4b3-810d65a0ed6f">
<img width="1440" alt="Screenshot 2023-11-22 at 12 49 18 PM" src="https://github.com/anisAronno/multipurpose-admin-panel-boilerplate/assets/38912435/dd983942-d183-4f87-9571-87d4e22ebf11">
<img width="1440" alt="Screenshot 2023-11-22 at 12 49 24 PM" src="https://github.com/anisAronno/multipurpose-admin-panel-boilerplate/assets/38912435/9da6ad98-e7a7-4f11-9196-65913eca3804">
<img width="1440" alt="Screenshot 2023-11-22 at 12 49 25 PM" src="https://github.com/anisAronno/multipurpose-admin-panel-boilerplate/assets/38912435/e3631b19-1761-411e-a6ef-602501804ddd">
